spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ieum?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    # log
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

ieum.upload.path: upload

# log
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security.web: trace

# jsessionid ????? ??X
server:
  servlet:
    session:
      tracking-modes: cookie